apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://grafana.github.io/helm-charts'
    targetRevision: "6.12.0"
    helm:
      values: |
        loki:
          schemaConfig:
            configs:
              - from: 2024-04-01
                store: tsdb
                object_store: s3
                schema: v13
                index:
                  prefix: loki_index_
                  period: 24h
          ingester:
            chunk_encoding: snappy
          tracing:
            enabled: true
          querier:
            # Default is 4, if you have enough memory and CPU you can increase, reduce if OOMing
            max_concurrent: 4
        
          # Should authentication be enabled
          auth_enabled: false
        chunksCache:
          # -- Specifies whether memcached based chunks-cache should be enabled
          enabled: true
          # -- Amount of memory allocated to chunks-cache for object storage (in MB).
          allocatedMemory: 512
          # -- Tolerations for chunks-cache pods
          tolerations:
          - key: node-role.kubernetes.io/control-plane
        
        # gateway:
        #   ingress:
        #     enabled: true
        #     hosts:
        #       - host: loki-gateway.home.loc
        #         paths:
        #           - path: /
        #             pathType: Prefix
        
        deploymentMode: SimpleScalable
        
        backend:
          replicas: 2
        read:
          replicas: 2
        write:
          replicas: 2
        
        # Enable minio for storage
        minio:
          enabled: true
        
        # Zero out replica counts of other deployment modes
        singleBinary:
          replicas: 0
        
        ingester:
          replicas: 0
        querier:
          replicas: 0
        queryFrontend:
          replicas: 0
        queryScheduler:
          replicas: 0
        distributor:
          replicas: 0
        compactor:
          replicas: 0
        indexGateway:
          replicas: 0
        bloomCompactor:
          replicas: 0
        bloomGateway:
          replicas: 0
         
    chart: loki
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: loki-stack
  syncPolicy:
    syncOptions:
      - CreateNamespace=true