apiVersion: v1
kind: Namespace
metadata:
  name: karma

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: karma
  namespace: karma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: karma
  template:
    metadata:
      labels:
        app: karma
    spec:
      containers:
      - name: karma-container
        image: ghcr.io/prymitive/karma:v0.118
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
        ports:
        - containerPort: 8080
        env:
        - name: CONFIG_FILE
          value: /etc/karma/karma.conf
        volumeMounts:
        - name: config-volume
          mountPath: /etc/karma
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30
      volumes:
      - name: config-volume
        configMap:
          name: karma-config

---

apiVersion: v1
kind: Service
metadata:
  name: karma-service
  namespace: karma
spec:
  selector:
    app: karma
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: karma-config
  namespace: karma
data:
  karma.conf: |
    alertmanager:
      interval: 60s
      servers:
        - name: alertmanager
          uri: http://alermanager:9093
          timeout: 10s
          proxy: true
          readonly: false
          #headers:
          #  X-Auth-Test: some-token-or-other-string
        #- name: client-auth
        #  uri: https://localhost:9093
        #  timeout: 10s
        #  tls:
        #    ca: /etc/ssl/certs/ca-bundle.crt
        #    cert: /etc/karma/client.pem
        #    key: /etc/karma/client.key
    annotations:
      default:
        hidden: false
      hidden:
        - help
      visible: []
    #custom:
    #  css: /custom.css
    #  js: /custom.js
    debug: false
    filters:
      default:
        - "@receiver=by-cluster-service"
    #karma:
    #  name: karma-prod
    labels:
      color:
        static:
          - job
        unique:
          - cluster
          - instance
          - "@receiver"
      keep: []
      strip: []
    listen:
      address: "0.0.0.0"
      port: 8080
      prefix: /
     # cors:
     #   allowedOrigins:
     #     - https://example.com
    log:
      config: false
      level: info
    #silences:
    #  comments:
    #    linkDetect:
    #      rules:
    #        - regex: "(DEVOPS-[0-9]+)"
    #          uriTemplate: https://jira.example.com/browse/$1
    receivers:
      keep: []
      strip: []
    silenceForm:
      strip:
        labels:
          - job
      defaultAlertmanagers:
        - local
    ui:
      refresh: 30s
      hideFiltersWhenIdle: true
      colorTitlebar: false
      minimalGroupWidth: 420
      alertsPerGroup: 5
      collapseGroups: collapsedOnMobile