apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: default-nginx-ingress
  namespace: ingress-nginx
  annotations:
    nginx.ingress.kubernetes.io/server-snippet: |
      location = / {
      add_header Content-Type text/plain;
      return 200 "OK \n";
      }
      location = /robots.txt {
        add_header Content-Type text/plain;
        return 200 "User-agent: *\nDisallow: /\n";
      }
      location ~* / {
        add_header Content-Type text/plain;
        return 444;
      }
      more_clear_headers Server always;
      more_set_headers "Server: ngx" always;
spec:
  rules:
  - host: ""
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: does-not-matter
            port:
              number: 80
