apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoria-metrics
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://victoriametrics.github.io/helm-charts/'
    targetRevision: 0.33.3
    helm:
      parameters:
        - name: nameOverride
          value: operator
    chart: victoria-metrics-operator
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: vm
  syncPolicy:
    syncOptions:
      - CreateNamespace=true