apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoria-metrics
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://victoriametrics.github.io/helm-charts/'
    targetRevision: 0.25.5
    helm:
      parameters:
#        - name: nameOverride
#          value: vm
         - name: prometheus-node-exporter.enabled
           value: false
         - name: kube-state-metrics.enabled
           value: false
         - name: grafana.enabled
           value: false
    chart: victoria-metrics-k8s-stack
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: vm
  syncPolicy:
    syncOptions:
      - CreateNamespace=true